package main

import (
	"database/sql"
	"fmt"
	"kasir-api/config"
	"log"
	"os"

	_ "github.com/lib/pq"
)

func main() {
	// Load config DB
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatal("❌ Config Error:", err)
	}

	db, err := sql.Open("postgres", cfg.GetDatabaseURL())
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatal("❌ DB Connection Failed:", err)
	}

	// Output File
	file, err := os.Create("database/current_schema_report.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	write(file, "=== CURRENT DATABASE SCHEMA REPORT ===\n")
	write(file, "Generated by tools/check_db_schema.go\n\n")

	// Get Tables
	rows, err := db.Query(`
		SELECT table_name 
		FROM information_schema.tables 
		WHERE table_schema = 'public' 
		ORDER BY table_name;
	`)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var tableName string
		rows.Scan(&tableName)
		write(file, fmt.Sprintf("TABLE: %s\n", tableName))
		write(file, "----------------------------------------\n")

		// Get Columns
		cols, err := db.Query(fmt.Sprintf(`
			SELECT column_name, data_type, is_nullable, column_default 
			FROM information_schema.columns 
			WHERE table_name = '%s' 
			ORDER BY ordinal_position;
		`, tableName))
		if err != nil {
			log.Println("Error getting columns:", err)
			continue
		}

		for cols.Next() {
			var colName, dataType, isNullable string
			var colDefault sql.NullString
			cols.Scan(&colName, &dataType, &isNullable, &colDefault)

			defVal := ""
			if colDefault.Valid {
				defVal = fmt.Sprintf(" [Default: %s]", colDefault.String)
			}
			write(file, fmt.Sprintf("  - %-20s : %s (%s)%s\n", colName, dataType, isNullable, defVal))
		}
		cols.Close()
		write(file, "\n")
	}

	fmt.Println("✅ Schema Report Generated: database/current_schema_report.txt")
}

func write(f *os.File, s string) {
	if _, err := f.WriteString(s); err != nil {
		log.Println("Error writing to file:", err)
	}
}
